spring:
  application:
    name: "taskmasterai"

  #Database Configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  #ORM Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: ${JWT_EXPIRATION_MS}
  refresh-token-expiry: ${JWT_REFRESH_TOKEN_DAYS}

application:
  url: ${APPLICATION_URL}

springdoc:
  api-docs:
    enabled: true


management:
  endpoint:
    health:
      access: read_only


